// Compile-only public API smoke. This file is included by the root type-check
// and intentionally produces no JavaScript; it verifies that both source entry
// points expose the complete documented type surface with identical contracts.

import type {
	CesiumGroundAppearance,
	CesiumGroundAppearanceOptions,
	CesiumGroundAppearanceOwner,
	CesiumGroundMaterial,
	CesiumGroundMaterialAppearance,
	CesiumGroundMaterialAppearanceOptions,
	CesiumGroundMaterialError,
	CesiumGroundMaterialErrorCode,
	CesiumGroundMaterialEventMap,
	CesiumGroundMaterialOptions,
	CesiumGroundRawShaderAppearance,
	CesiumGroundRawShaderAppearanceEventMap,
	CesiumGroundRawShaderAppearanceOptions,
	ColorGroundMaterialOptions,
	FlowLineMaterialOptions,
	GroundColorInput,
	GroundDefines,
	GroundDefineValue,
	GroundMaterialFactory,
	GroundPrimitiveKind,
	GroundRawShaderBuildContext,
	GroundRenderPass,
	GroundSystemUniforms,
	GroundUserUniforms,
	PolylineDashMaterialOptions,
	PulsePointMaterialOptions,
	ScalePulseMaterialOptions,
	TexturedDecalMaterialOptions,
} from '../../../src/cesium-three-ground';
import type {
	CesiumGroundAppearance as GroundCesiumGroundAppearance,
	CesiumGroundAppearanceOptions as GroundCesiumGroundAppearanceOptions,
	CesiumGroundAppearanceOwner as GroundCesiumGroundAppearanceOwner,
	CesiumGroundMaterial as GroundCesiumGroundMaterial,
	CesiumGroundMaterialAppearance as GroundCesiumGroundMaterialAppearance,
	CesiumGroundMaterialAppearanceOptions as GroundCesiumGroundMaterialAppearanceOptions,
	CesiumGroundMaterialError as GroundCesiumGroundMaterialError,
	CesiumGroundMaterialErrorCode as GroundCesiumGroundMaterialErrorCode,
	CesiumGroundMaterialEventMap as GroundCesiumGroundMaterialEventMap,
	CesiumGroundMaterialOptions as GroundCesiumGroundMaterialOptions,
	CesiumGroundRawShaderAppearance as GroundCesiumGroundRawShaderAppearance,
	CesiumGroundRawShaderAppearanceEventMap as GroundCesiumGroundRawShaderAppearanceEventMap,
	CesiumGroundRawShaderAppearanceOptions as GroundCesiumGroundRawShaderAppearanceOptions,
	ColorGroundMaterialOptions as GroundColorGroundMaterialOptions,
	FlowLineMaterialOptions as GroundFlowLineMaterialOptions,
	GroundColorInput as GroundGroundColorInput,
	GroundDefines as GroundGroundDefines,
	GroundDefineValue as GroundGroundDefineValue,
	GroundMaterialFactory as GroundGroundMaterialFactory,
	GroundPrimitiveKind as GroundGroundPrimitiveKind,
	GroundRawShaderBuildContext as GroundGroundRawShaderBuildContext,
	GroundRenderPass as GroundGroundRenderPass,
	GroundSystemUniforms as GroundGroundSystemUniforms,
	GroundUserUniforms as GroundGroundUserUniforms,
	PolylineDashMaterialOptions as GroundPolylineDashMaterialOptions,
	PulsePointMaterialOptions as GroundPulsePointMaterialOptions,
	ScalePulseMaterialOptions as GroundScalePulseMaterialOptions,
	TexturedDecalMaterialOptions as GroundTexturedDecalMaterialOptions,
} from '../../../src/lib/ground';

type Equal<A, B> =
	( <T>() => T extends A ? 1 : 2 ) extends ( <T>() => T extends B ? 1 : 2 )
		? true
		: false;
type Assert<T extends true> = T;

/** Every tuple entry must remain true or TypeScript rejects the public build. */
export type PublicGroundApiEntryParity = [
	Assert<Equal<CesiumGroundAppearance, GroundCesiumGroundAppearance>>,
	Assert<Equal<CesiumGroundAppearanceOptions, GroundCesiumGroundAppearanceOptions>>,
	Assert<Equal<CesiumGroundAppearanceOwner, GroundCesiumGroundAppearanceOwner>>,
	Assert<Equal<CesiumGroundMaterial, GroundCesiumGroundMaterial>>,
	Assert<Equal<CesiumGroundMaterialAppearance, GroundCesiumGroundMaterialAppearance>>,
	Assert<Equal<CesiumGroundMaterialAppearanceOptions, GroundCesiumGroundMaterialAppearanceOptions>>,
	Assert<Equal<CesiumGroundMaterialError, GroundCesiumGroundMaterialError>>,
	Assert<Equal<CesiumGroundMaterialErrorCode, GroundCesiumGroundMaterialErrorCode>>,
	Assert<Equal<CesiumGroundMaterialEventMap, GroundCesiumGroundMaterialEventMap>>,
	Assert<Equal<CesiumGroundMaterialOptions, GroundCesiumGroundMaterialOptions>>,
	Assert<Equal<CesiumGroundRawShaderAppearance, GroundCesiumGroundRawShaderAppearance>>,
	Assert<Equal<CesiumGroundRawShaderAppearanceEventMap, GroundCesiumGroundRawShaderAppearanceEventMap>>,
	Assert<Equal<CesiumGroundRawShaderAppearanceOptions, GroundCesiumGroundRawShaderAppearanceOptions>>,
	Assert<Equal<ColorGroundMaterialOptions, GroundColorGroundMaterialOptions>>,
	Assert<Equal<FlowLineMaterialOptions, GroundFlowLineMaterialOptions>>,
	Assert<Equal<GroundColorInput, GroundGroundColorInput>>,
	Assert<Equal<GroundDefines, GroundGroundDefines>>,
	Assert<Equal<GroundDefineValue, GroundGroundDefineValue>>,
	Assert<Equal<GroundMaterialFactory, GroundGroundMaterialFactory>>,
	Assert<Equal<GroundPrimitiveKind, GroundGroundPrimitiveKind>>,
	Assert<Equal<GroundRawShaderBuildContext, GroundGroundRawShaderBuildContext>>,
	Assert<Equal<GroundRenderPass, GroundGroundRenderPass>>,
	Assert<Equal<GroundSystemUniforms, GroundGroundSystemUniforms>>,
	Assert<Equal<GroundUserUniforms, GroundGroundUserUniforms>>,
	Assert<Equal<PolylineDashMaterialOptions, GroundPolylineDashMaterialOptions>>,
	Assert<Equal<PulsePointMaterialOptions, GroundPulsePointMaterialOptions>>,
	Assert<Equal<ScalePulseMaterialOptions, GroundScalePulseMaterialOptions>>,
	Assert<Equal<TexturedDecalMaterialOptions, GroundTexturedDecalMaterialOptions>>,
];
