// ============================================================
// circle/circle-extents.ts
// Layer: Cesium-coupled circle ground adapter support.
// Role: compute planar uniforms for a Cesium CircleGeometry shadow volume
//       while keeping the geometry source of truth inside cesium-ground-source.
// Dependencies: local WGS84 math helpers and Three.js vectors.
// Consumed by: primitives.ts CesiumGroundCirclePrimitive.
// ============================================================

import { Matrix4, Vector2, Vector3, Vector4 } from 'three';

import { createCartographic } from '../math/cartographic';
import { cartographicToCartesian } from '../math/ellipsoid';
import { eastNorthUpToFixedFrame } from '../math/enu-frame';
import { matrix4MultiplyByPoint } from '../math/matrix4-helpers';
import { encodeVec3RTE } from '../math/rte-encoding';
import type { PlanarExtents } from '../types';

export interface CirclePlanarExtents {
	extents: PlanarExtents;
	centerMeters: Vector2;
	fillRadiusMeters: number;
	renderRadiusMeters: number;
}

const _circleCenterCarto = createCartographic();
const _circleCenterEcef = new Vector3();
const _circleEnuToEcef = new Matrix4();
const _circleCornerEnu = new Vector3();
const _circleSwEcef = new Vector3();
const _circleSeEcef = new Vector3();
const _circleNwEcef = new Vector3();
const _circleSwHigh = new Vector3();
const _circleSwLow = new Vector3();

/**
 * Computes the planar meter frame used by Cesium's ShadowVolumeAppearance.
 *
 * The circle mesh itself is still generated by Cesium CircleGeometry. This
 * helper only supplies the Three-side batch-table uniforms used by the shared
 * classification shaders. The local frame is centered at the WGS84 circle
 * center and spans the rendered radius, including the optional stroke band.
 *
 * @param centerLongitudeDegrees Circle center longitude in degrees.
 * @param centerLatitudeDegrees Circle center latitude in degrees.
 * @param fillRadiusMeters Public Cesium circle radius in meters.
 * @param renderRadiusMeters Radius used for the shadow volume, including stroke.
 * @returns Planar extents plus circle style uniforms in the same meter frame.
 */
export function computeCirclePlanarExtents(
	centerLongitudeDegrees: number,
	centerLatitudeDegrees: number,
	fillRadiusMeters: number,
	renderRadiusMeters: number,
): CirclePlanarExtents {
	_circleCenterCarto.longitude = centerLongitudeDegrees * Math.PI / 180.0;
	_circleCenterCarto.latitude = centerLatitudeDegrees * Math.PI / 180.0;
	_circleCenterCarto.height = 0.0;
	cartographicToCartesian( _circleCenterCarto, _circleCenterEcef );
	eastNorthUpToFixedFrame( _circleCenterEcef, _circleEnuToEcef );

	_circleCornerEnu.set( - renderRadiusMeters, - renderRadiusMeters, 0.0 );
	matrix4MultiplyByPoint( _circleEnuToEcef, _circleCornerEnu, _circleSwEcef );

	_circleCornerEnu.set( renderRadiusMeters, - renderRadiusMeters, 0.0 );
	matrix4MultiplyByPoint( _circleEnuToEcef, _circleCornerEnu, _circleSeEcef );

	_circleCornerEnu.set( - renderRadiusMeters, renderRadiusMeters, 0.0 );
	matrix4MultiplyByPoint( _circleEnuToEcef, _circleCornerEnu, _circleNwEcef );

	const eastward = new Vector3(
		_circleSeEcef.x - _circleSwEcef.x,
		_circleSeEcef.y - _circleSwEcef.y,
		_circleSeEcef.z - _circleSwEcef.z,
	);
	const northward = new Vector3(
		_circleNwEcef.x - _circleSwEcef.x,
		_circleNwEcef.y - _circleSwEcef.y,
		_circleNwEcef.z - _circleSwEcef.z,
	);

	encodeVec3RTE( _circleSwEcef, _circleSwHigh, _circleSwLow );

	return {
		extents: {
			southWestHigh: new Vector3( _circleSwHigh.x, _circleSwHigh.y, _circleSwHigh.z ),
			southWestLow: new Vector3( _circleSwLow.x, _circleSwLow.y, _circleSwLow.z ),
			eastward,
			northward,
			uvMinAndExtents: new Vector4( 0.0, 0.0, 1.0, 1.0 ),
			uMaxVmax: new Vector4( 0.0, 1.0, 1.0, 0.0 ),
			innerMetersRect: new Vector4(
				renderRadiusMeters - fillRadiusMeters,
				renderRadiusMeters - fillRadiusMeters,
				renderRadiusMeters + fillRadiusMeters,
				renderRadiusMeters + fillRadiusMeters,
			),
		},
		centerMeters: new Vector2( renderRadiusMeters, renderRadiusMeters ),
		fillRadiusMeters,
		renderRadiusMeters,
	};
}
